# Generated by Django 5.0.2 on 2024-03-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("desciption", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_content", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("ONE_CHOICE", "One choice"),
                            ("MULTIPLE_CHOICES", "Multiple choices"),
                        ],
                        default="TEXT",
                        max_length=64,
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
                    ),
                ),
            ],
        ),
    ]
