# Generated by Django 5.0.2 on 2024-03-07 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_poll_passed_users_alter_multiplechoicesanswer_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="passed_users",
        ),
    ]
